### ISSUE TITLE
TImezone name

### ISSUE THREAD

**Issue by ccakes** [timefyi/time.fyi#11]
A nice option would be to show the timezone name (eg Pacific Time, Mountain Time) either on the panel somewhere or maybe when hovering the GMT offset?

![image](https://github.com/timefyi/time.fyi/assets/103831/212b112f-f9cf-4115-87cc-df41859aff42)

As a non-American I can never remember the difference between Central and Mountain and this would be a big help!

**Comment by nilbuild** [comment]
Hovering over a card now shows the timezone name.

<img width="749" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/4ef04099-7fef-48a8-90d3-24f99be8a156">

I didn't add it to the card to avoid the clutter.
