### ISSUE TITLE
UTC vs GMT

### ISSUE THREAD

**Issue by inputvalidation** [timefyi/time.fyi#12]
Would it make sense to base time on UTC instead of GMT? That's even more universal.

https://stackoverflow.com/questions/48942916/what-is-the-difference-between-utc-and-gmt#:~:text=By%20the%20original%20definitions%20the,which%20blurs%20the%20distinction%20somewhat.

**Comment by leadenchopsticks** [comment]
+1. Timezones shall be relative to UTC, not GMT.

**Comment by nilbuild** [comment]
It doesn't matter in the current implementation.
