### ISSUE TITLE
Consider mentioning the timezone along with the city on the time cards

### ISSUE THREAD

**Issue by nibrahim** [timefyi/time.fyi#13]
![image](https://github.com/timefyi/time.fyi/assets/69051/529b75ea-8066-4c6f-ac63-27fe05d2a69a)

**Comment by nilbuild** [comment]
Hovering over a card now shows the timezone name.

<img width="749" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/4ef04099-7fef-48a8-90d3-24f99be8a156">

I didn't add it to the card to avoid the clutter.

**Comment by nibrahim** [comment]
How does this work on mobile where there's no hover?

**Comment by nilbuild** [comment]
Ah, that didn't cross my mind -- will do something about it. Thank you!
