### ISSUE TITLE
I wish that shareable link would keep the 12/24h setting too

### ISSUE THREAD

**Issue by MartyLake** [timefyi/time.fyi#16]
Hello,
Time in french is expressed as 24h setting. When sharing a link to other french people, I wish to share them in 24h setting.

Best,
PS: awesome website, great design

**Comment by nilbuild** [comment]
Thanks Marty! This [has been implemented](https://time.fyi/timezones?d=Europe%2FLondon%3Dx%3DLondon%2CEurope%2FParis%3Dx%3DParis-primary&t=2024-04-18T13%3A45%3A01.991%2B02%3A00&h=24).
