### ISSUE TITLE
Save timezones, todos, routines to an account

### ISSUE THREAD

**Issue by onewildgamer** [timefyi/time.fyi#18]
I really appreciate the effort that went into creating this multitude of tools in a single place. I wish this had an option to save my preferences in a centralised place accessible via an email/userid.

**Comment by nilbuild** [comment]
It is one of the priority items and will be live in the next few weeks.

I just wanted to come up with the datastructure and basic functionalities that I wanted, so postponed it. Everything is clear how it should work so it will be live soon.
