### ISSUE TITLE
Kyiv not Kiev

### ISSUE THREAD

**Issue by i474232898** [timefyi/time.fyi#21]
Please, rename "Kiev" to "Kyiv". 

"Kyiv" is the official Ukrainian name for the capital, reflecting the correct Ukrainian pronunciation. "Kiev" is derived from the Russian transliteration and reflects Russian pronunciation

https://en.wikipedia.org/wiki/KyivNotKiev

**Comment by nilbuild** [comment]
Thank you for opening the issue but it's already `Kyiv`. 

<img width="381" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/7626d57b-b7ac-4d76-a7da-c0c8c06bcd86">

Where did you see Kiev mentioned? Can you please share the screenshot?

**Comment by i474232898** [comment]
That's probably some cached value. After deleting it and adding again - it's gone.
Thank you!

<img width="1344" alt="Screenshot 2024-05-09 at 2 34 45 PM" src="https://github.com/timefyi/time.fyi/assets/8483225/3cf57048-0714-496a-8d2c-cc92722c93d5">
