### ISSUE TITLE
Feature request: map in the world clock

### ISSUE THREAD

**Issue by afiorillo** [timefyi/time.fyi#23]
The world clock works nicely as a set of cards but doesn't give any spatial information. A nice enhancement might be some map display with pins corresponding to the named locations, perhaps highlighting the currently selected city. There are [open resources](https://github.com/treyerl/timezones) for the timezones shape files and the map could be straightforward to render with [Leaflet](https://leafletjs.com/)

**Comment by nilbuild** [comment]
This won't add much value at the moment. I am prioritizing on things that would _really_ help with productivity and time management. However, I have added this in the backlog and will get back to it once time allows. Thank you for reporting 🙏
