### ISSUE TITLE
Public holidays displayed in timezones

### ISSUE THREAD

**Issue by altbert** [timefyi/time.fyi#28]
Hi! I propose adding a feature that displays the public holidays of each country. This might be useful when coordinating dates with someone in a different timezone.

**Comment by altbert** [comment]
[This link may be useful if implemented](https://opendata.stackexchange.com/questions/1926/list-of-public-holidays-by-countries)

**Comment by nilbuild** [comment]
Thank you for reporting, that's a good idea. I will put it in the backlog and will pick it up once we implement calendars.
