### ISSUE TITLE
Inconsistent UI for timezones

### ISSUE THREAD

**Issue by blakegearin** [timefyi/time.fyi#29]
## Summary

The same URL shows different UIs on the same device depending on what browser I use.

  ```url
  https://time.fyi/timezones?d=America%2FLos_Angeles%3Dx%3DSan%20Francisco%2CAmerica%2FDenver-primary%2CAmerica%2FChicago%3Dx%3DSt.%20Louis%2CAmerica%2FNew_York%3Dx%3DBrooklyn&t=&h=24
  ```

## Screenshots

- Arc

  ![image](https://github.com/user-attachments/assets/a60ddebd-57f8-4107-b653-8b0d2bf2342e)

- Firefox

  ![image](https://github.com/user-attachments/assets/d9510f94-9f0d-4d7f-b972-d51e3462e331)

## Notes

Not sure why this would be happening. I prefer the Arc version.

**Comment by nilbuild** [comment]
You can switch the UI from the newly added button in the top-right corner.

<img width="375" alt="image" src="https://github.com/user-attachments/assets/c9a03970-bfd2-4603-a8c8-9a98bf94ccfe">
