### ISSUE TITLE
Add title and labels on the timezone box

### ISSUE THREAD

**Issue by alberto-lopez** [timefyi/time.fyi#31]
It would be very useful to be able to create a "Title" and some "Lables" on the Timezone. This will allow, for example, to set the names of the offices, or partner companies, or even colleagues for remote companies.

<img width="368" alt="Screenshot 2024-08-14 at 12 33 31" src="https://github.com/user-attachments/assets/cdca4260-6e92-41df-9a8c-50a151c6dd90">

**Comment by nilbuild** [comment]
This is now possible with teams feature.

<img width="920" alt="image" src="https://github.com/user-attachments/assets/6dfc2a2d-416b-4bc6-a95f-9bfc85cb9dfb">
