### ISSUE TITLE
Incorrect spelling of the city Kyiv

### ISSUE THREAD

**Issue by OlehDuts** [timefyi/time.fyi#33]
Kiev is not correct, please change to the correct spelling (Kyiv)

**Comment by nilbuild** [comment]
It is showint the correct spellings. Could you please describe how to reproduce this?

<img width="939" alt="image" src="https://github.com/user-attachments/assets/75113fa8-025e-4e01-b549-5ad6b2b8d55f">

**Comment by OlehDuts** [comment]
the default value was Kiev. I am in Ukraine

If you search, then everything is also good

**Comment by OlehDuts** [comment]
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/bed8ad07-0026-4f41-81bb-4cf42ca120da">
also, if you write with an error in the search field, it will find Kyiv. Maybe there's an alias you need to get rid of.

**Comment by nilbuild** [comment]
This alias is intentional so that if someone who doesn't know has a typo will still show the result.
