### ISSUE TITLE
Notes on timezones

### ISSUE THREAD

**Issue by FedeBev** [timefyi/time.fyi#34]
Hi there,

IMO it would be cool to have the possibility of adding notes on the timezone cards, I personally would use that to annotate the name of the colleagues in every timezone

Thanks
Cool project

**Comment by nilbuild** [comment]
You can do that from the newly launched team feature

<img width="920" alt="image" src="https://github.com/user-attachments/assets/d17b2e39-69a6-4cdf-a99c-97678c8a6a4d">
