### ISSUE TITLE
Issue with the spacing between routine cards

### ISSUE THREAD

**Issue by rohitb47** [timefyi/time.fyi#35]
Hi @kamranahmedse, Thanks for building time.fyi, it's an amazing tool, and I love it 😻.

I identified an issue with the spacing between the cards on the routine's page, I have attached the screenshot of how it renders on a desktop, the cards are sticking to each other, I think there should be a bit of spacing. 

<img width="1113" alt="Screenshot 2024-08-24 at 3 15 37 PM" src="https://github.com/user-attachments/assets/a6aee78d-d643-412d-84c1-33a58cbfb8ea">

**Comment by aryanbhat** [comment]
@kamranahmedse can i work on this issue ??

**Comment by nilbuild** [comment]
This has been fixed. Thank you!
